-- 
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (20, 'Jab³ka', 54, 0.4, 12, 11.8, 0, 2.3, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (21, 'Morele', 60, 1.4, 11.5, 7.7, 0.4, 2.3, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (22, 'Szparagi', 17, 1.9, 1.3, 1.2, 0.2, 1.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (23, 'Awokado', 188, 2.6, 1.5, 1.4, 18.1, 6.4, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (24, 'Banany', 86, 1.2, 18.8, 18.2, 0.2, 2, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (25, 'Fasola bia³a', 114, 7.5, 14.5, 0, 0.6, 10.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (26, 'Wo³owina', 198, 30, 0.5, 0, 8.5, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (27, 'Je¿yny', 58, 1.2, 8.5, 6.8, 1, 5.2, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (28, 'Jagody', 75, 0.6, 14.5, 14, 0.2, 6.6, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (29, 'Pieczywo bia³e', 283, 8.4, 58, 2, 1.9, 3.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (30, 'Pieczywo wieloziarniste', 262, 9.5, 45, 2, 3.4, 5.9, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (31, 'Broku³y', 29, 3.2, 2, 2, 0.1, 4.1, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (32, 'Brukselki', 25, 3, 3.4, 3.1, 0, 4.8, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (33, 'Kasza bulgur', 375, 9.5, 80, 2.2, 1, 2, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (34, 'Mas³o', 735, 0.7, 0.7, 0.7, 82.5, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (35, 'Marchew', 27, 0.8, 4.7, 4.4, 0, 2.9, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (36, 'Kalafior', 20, 1.9, 2.2, 2, 0, 2.1, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (37, 'Pierœ z kurczaka', 157, 30, 0, 0, 4, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (38, 'Nó¿ka z kurczaka', 103, 20.6, 0, 0, 2.3, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (39, 'Kukurydza', 354, 9.2, 65.5, 1.5, 3.8, 9.2, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (40, 'Kaczka', 225, 18.1, 0, 0, 17.2, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (41, 'Jajka', 235, 13.5, 1, 0, 20, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (42, 'Paluszki rybne', 247, 15.1, 18.3, 1.4, 12.4, 1.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (43, 'Frytki', 307, 5.5, 46, 0, 10.5, 3, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (44, 'Winogrona', 57, 0.5, 13.5, 13.3, 0, 0.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (45, 'Szynka', 201, 21.5, 1, 1, 12.5, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (46, 'Orzechy laskowe', 667, 14.2, 10.6, 8.5, 62.5, 7.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (47, 'Miód', 308, 0.4, 75.5, 75.1, 0, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (48, 'D¿em', 247, 0.4, 60, 59, 0, 1.5, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (49, 'Nerki (wieprzowina)', 116, 16.5, 0.8, 0, 5.2, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (50, 'Kiwi', 48, 1, 10.3, 7.5, 0.2, 0.7, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (51, 'Sa³ata', 11, 1.3, 1, 1, 0.2, 1.3, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (52, 'W¹tróbka (wieprzowina)', 132, 22.2, 2, 2, 3.9, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (53, 'Majonez', 741, 1.7, 2.5, 2.5, 82, 0, 0)
INSERT INTO [dbo].[Produkty] (ID_Produkty, Nazwa, Kcal, Bialko, Weglowodany, Cukier, Tluszcz, Blonnik, Sol) VALUES (54, 'Mleko', 62, 3.7, 4.3, 4.3, 3.4, 0, 0)
