INSERT [dbo].[Posilki] VALUES (8, 'œniadanie8', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (9, 'œniadanie9', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (10, 'œniadanie10', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (11, 'œniadanie11', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (12, 'œniadanie12', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (13, 'œniadanie13', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (14, 'œniadanie14', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (15, 'œniadanie15', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (16, 'œniadanie16', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (17, 'œniadanie17', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (18, 'œniadanie18', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (19, 'œniadanie19', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (20, 'œniadanie20', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (21, 'œniadanie21', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (22, 'œniadanie22', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (23, 'œniadanie23', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (24, 'œniadanie24', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (25, 'œniadanie25', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (26, 'œniadanie26', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (27, 'œniadanie27', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (28, 'œniadanie28', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (29, 'œniadanie29', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (30, 'œniadanie30', 'œniadanie')
INSERT [dbo].[Posilki] VALUES (31, 'œniadanie31', 'œniadanie')
-- yes we had breakfast, but what about second breakfast?
INSERT [dbo].[Posilki] VALUES (32, 'drugie œniadanie8', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (33, 'drugie œniadanie9', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (34, 'drugie œniadanie10', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (35, 'drugie œniadanie11', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (36, 'drugie œniadanie12', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (37, 'drugie œniadanie13', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (38, 'drugie œniadanie14', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (39, 'drugie œniadanie15', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (40, 'drugie œniadanie16', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (41, 'drugie œniadanie17', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (42, 'drugie œniadanie18', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (43, 'drugie œniadanie19', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (44, 'drugie œniadanie20', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (45, 'drugie œniadanie21', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (46, 'drugie œniadanie22', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (47, 'drugie œniadanie23', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (48, 'drugie œniadanie24', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (49, 'drugie œniadanie25', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (50, 'drugie œniadanie26', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (51, 'drugie œniadanie27', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (52, 'drugie œniadanie28', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (53, 'drugie œniadanie29', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (54, 'drugie œniadanie30', 'drugie œniadanie')
INSERT [dbo].[Posilki] VALUES (55, 'drugie œniadanie31', 'drugie œniadanie')
-- ile roboty z tym jprdl, teraz obiady
INSERT [dbo].[Posilki] VALUES (56, 'obiad8', 'obiad')
INSERT [dbo].[Posilki] VALUES (57, 'obiad9', 'obiad')
INSERT [dbo].[Posilki] VALUES (58, 'obiad10', 'obiad')
INSERT [dbo].[Posilki] VALUES (59, 'obiad11', 'obiad')
INSERT [dbo].[Posilki] VALUES (60, 'obiad12', 'obiad')
INSERT [dbo].[Posilki] VALUES (61, 'obiad13', 'obiad')
INSERT [dbo].[Posilki] VALUES (62, 'obiad14', 'obiad')
INSERT [dbo].[Posilki] VALUES (63, 'obiad15', 'obiad')
INSERT [dbo].[Posilki] VALUES (64, 'obiad16', 'obiad')
INSERT [dbo].[Posilki] VALUES (65, 'obiad17', 'obiad')
INSERT [dbo].[Posilki] VALUES (66, 'obiad18', 'obiad')
INSERT [dbo].[Posilki] VALUES (67, 'obiad19', 'obiad')
INSERT [dbo].[Posilki] VALUES (68, 'obiad20', 'obiad')
INSERT [dbo].[Posilki] VALUES (69, 'obiad21', 'obiad')
INSERT [dbo].[Posilki] VALUES (70, 'obiad22', 'obiad')
INSERT [dbo].[Posilki] VALUES (71, 'obiad23', 'obiad')
INSERT [dbo].[Posilki] VALUES (72, 'obiad24', 'obiad')
INSERT [dbo].[Posilki] VALUES (73, 'obiad25', 'obiad')
INSERT [dbo].[Posilki] VALUES (74, 'obiad26', 'obiad')
INSERT [dbo].[Posilki] VALUES (75, 'obiad27', 'obiad')
INSERT [dbo].[Posilki] VALUES (76, 'obiad28', 'obiad')
INSERT [dbo].[Posilki] VALUES (77, 'obiad29', 'obiad')
INSERT [dbo].[Posilki] VALUES (78, 'obiad30', 'obiad')
INSERT [dbo].[Posilki] VALUES (79, 'obiad31', 'obiad')
-- podwieczorki
INSERT [dbo].[Posilki] VALUES (80, 'podwieczorek8', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (81, 'podwieczorek9', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (82, 'podwieczorek10', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (83, 'podwieczorek11', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (84, 'podwieczorek12', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (85, 'podwieczorek13', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (86, 'podwieczorek14', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (87, 'podwieczorek15', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (88, 'podwieczorek16', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (89, 'podwieczorek17', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (90, 'podwieczorek18', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (91, 'podwieczorek19', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (92, 'podwieczorek20', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (93, 'podwieczorek21', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (94, 'podwieczorek22', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (95, 'podwieczorek23', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (96, 'podwieczorek24', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (97, 'podwieczorek25', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (98, 'podwieczorek26', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (99, 'podwieczorek27', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (100, 'podwieczorek28', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (101, 'podwieczorek29', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (102, 'podwieczorek30', 'podwieczorek')
INSERT [dbo].[Posilki] VALUES (103, 'podwieczorek31', 'podwieczorek')
-- kolacje
INSERT [dbo].[Posilki] VALUES (104, 'kolacja8', 'kolacja')
INSERT [dbo].[Posilki] VALUES (105, 'kolacja9', 'kolacja')
INSERT [dbo].[Posilki] VALUES (106, 'kolacja10', 'kolacja')
INSERT [dbo].[Posilki] VALUES (107, 'kolacja11', 'kolacja')
INSERT [dbo].[Posilki] VALUES (108, 'kolacja12', 'kolacja')
INSERT [dbo].[Posilki] VALUES (109, 'kolacja13', 'kolacja')
INSERT [dbo].[Posilki] VALUES (110, 'kolacja14', 'kolacja')
INSERT [dbo].[Posilki] VALUES (111, 'kolacja15', 'kolacja')
INSERT [dbo].[Posilki] VALUES (112, 'kolacja16', 'kolacja')
INSERT [dbo].[Posilki] VALUES (113, 'kolacja17', 'kolacja')
INSERT [dbo].[Posilki] VALUES (114, 'kolacja18', 'kolacja')
INSERT [dbo].[Posilki] VALUES (115, 'kolacja19', 'kolacja')
INSERT [dbo].[Posilki] VALUES (116, 'kolacja20', 'kolacja')
INSERT [dbo].[Posilki] VALUES (117, 'kolacja21', 'kolacja')
INSERT [dbo].[Posilki] VALUES (118, 'kolacja22', 'kolacja')
INSERT [dbo].[Posilki] VALUES (119, 'kolacja23', 'kolacja')
INSERT [dbo].[Posilki] VALUES (120, 'kolacja24', 'kolacja')
INSERT [dbo].[Posilki] VALUES (121, 'kolacja25', 'kolacja')
INSERT [dbo].[Posilki] VALUES (122, 'kolacja26', 'kolacja')
INSERT [dbo].[Posilki] VALUES (123, 'kolacja27', 'kolacja')
INSERT [dbo].[Posilki] VALUES (124, 'kolacja28', 'kolacja')
INSERT [dbo].[Posilki] VALUES (125, 'kolacja29', 'kolacja')
INSERT [dbo].[Posilki] VALUES (126, 'kolacja30', 'kolacja')
INSERT [dbo].[Posilki] VALUES (127, 'kolacja31', 'kolacja')