-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2020-10-23 11:57:02 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE Cwiczenia 
    (
     ID_Cwiczenia NUMERIC (28) NOT NULL , 
     Nazwa VARCHAR (30) NOT NULL , 
     Opis VARCHAR (500) NOT NULL , 
     Powtorzenia NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Cwiczenia ADD CONSTRAINT Cwiczenia_PK PRIMARY KEY CLUSTERED (ID_Cwiczenia)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE CwiczeniaTrening 
    (
     ID_Treningi1 NUMERIC (28) NOT NULL , 
     ID_Cwiczenia1 NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE CwiczeniaTrening ADD CONSTRAINT CwiczeniaTrening_PK PRIMARY KEY CLUSTERED (ID_Treningi1, ID_Cwiczenia1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ListaZakupow 
    (
     ID_ListaZakupow NUMERIC (28) NOT NULL , 
     Nazwa VARCHAR (30) NOT NULL , 
     ID_Uzytkownik1 NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE ListaZakupow ADD CONSTRAINT ListaZakupow_PK PRIMARY KEY CLUSTERED (ID_ListaZakupow)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ListaZakupowProdukty 
    (
     ID_Produkty1 NUMERIC (28) NOT NULL , 
     ID_ListaZakupow1 NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE ListaZakupowProdukty ADD CONSTRAINT ListaZakupowProdukty_PK PRIMARY KEY CLUSTERED (ID_Produkty1, ID_ListaZakupow1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Posilki 
    (
     ID_Posilki NUMERIC (28) NOT NULL , 
     Przepis VARCHAR (500) NOT NULL , 
     Kategoria VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE Posilki ADD CONSTRAINT Posilki_PK PRIMARY KEY CLUSTERED (ID_Posilki)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Produkty 
    (
     ID_Produkty NUMERIC (28) NOT NULL , 
     Kcal NUMERIC (28) NOT NULL , 
     Tluszcz NUMERIC (28) NOT NULL , 
     Weglowodany NUMERIC (28) NOT NULL , 
     Cukier NUMERIC (28) , 
     Blonnik NUMERIC (28) NOT NULL , 
     Bialko NUMERIC (28) NOT NULL , 
     Sol NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Produkty ADD CONSTRAINT Produkty_PK PRIMARY KEY CLUSTERED (ID_Produkty)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ProduktyPosilki 
    (
     ID_Posilki1 NUMERIC (28) NOT NULL , 
     ID_Produkty1 NUMERIC (28) NOT NULL , 
     Ilosc NUMERIC (28) NOT NULL , 
     Jednostka VARCHAR (30) NOT NULL 
    )
GO

ALTER TABLE ProduktyPosilki ADD CONSTRAINT ProduktyPosilki_PK PRIMARY KEY CLUSTERED (ID_Posilki1, ID_Produkty1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Treningi 
    (
     ID_Treningi NUMERIC (28) NOT NULL , 
     Czas NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Treningi ADD CONSTRAINT Treningi_PK PRIMARY KEY CLUSTERED (ID_Treningi)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Uzytkownik 
    (
     ID_Uzytkownik NUMERIC (28) NOT NULL , 
     Imie VARCHAR (30) NOT NULL , 
     Email VARCHAR (30) NOT NULL , 
     Plec NUMERIC (28) NOT NULL , 
     Waga NUMERIC (28) NOT NULL , 
     Wzrost NUMERIC (28) NOT NULL , 
     Wiek NUMERIC (28) NOT NULL , 
     Cel NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE Uzytkownik ADD CONSTRAINT Uzytkownik_PK PRIMARY KEY CLUSTERED (ID_Uzytkownik)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE UzytkownikPosilki 
    (
     Dzien NUMERIC (28) NOT NULL , 
     ID_Uzytkownik1 NUMERIC (28) NOT NULL , 
     ID_Posilki1 NUMERIC (28) NOT NULL 
    )
GO

ALTER TABLE UzytkownikPosilki ADD CONSTRAINT UzytkownikPosilki_PK PRIMARY KEY CLUSTERED (Dzien, ID_Uzytkownik1, ID_Posilki1)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE CwiczeniaTrening 
    ADD CONSTRAINT CwiczeniaTrening_Cwiczenia_FK FOREIGN KEY 
    ( 
     ID_Cwiczenia1
    ) 
    REFERENCES Cwiczenia 
    ( 
     ID_Cwiczenia 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CwiczeniaTrening 
    ADD CONSTRAINT CwiczeniaTrening_Treningi_FK FOREIGN KEY 
    ( 
     ID_Treningi1
    ) 
    REFERENCES Treningi 
    ( 
     ID_Treningi 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ListaZakupow 
    ADD CONSTRAINT ListaZakupow_Uzytkownik_FK FOREIGN KEY 
    ( 
     ID_Uzytkownik1
    ) 
    REFERENCES Uzytkownik 
    ( 
     ID_Uzytkownik 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ListaZakupowProdukty 
    ADD CONSTRAINT ListaZakupowProdukty_ListaZakupow_FK FOREIGN KEY 
    ( 
     ID_ListaZakupow1
    ) 
    REFERENCES ListaZakupow 
    ( 
     ID_ListaZakupow 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ListaZakupowProdukty 
    ADD CONSTRAINT ListaZakupowProdukty_Produkty_FK FOREIGN KEY 
    ( 
     ID_Produkty1
    ) 
    REFERENCES Produkty 
    ( 
     ID_Produkty 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ProduktyPosilki 
    ADD CONSTRAINT ProduktyPosilki_Posilki_FK FOREIGN KEY 
    ( 
     ID_Posilki1
    ) 
    REFERENCES Posilki 
    ( 
     ID_Posilki 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE ProduktyPosilki 
    ADD CONSTRAINT ProduktyPosilki_Produkty_FK FOREIGN KEY 
    ( 
     ID_Produkty1
    ) 
    REFERENCES Produkty 
    ( 
     ID_Produkty 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UzytkownikPosilki 
    ADD CONSTRAINT UzytkownikPosilki_Posilki_FK FOREIGN KEY 
    ( 
     ID_Posilki1
    ) 
    REFERENCES Posilki 
    ( 
     ID_Posilki 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO

ALTER TABLE UzytkownikPosilki 
    ADD CONSTRAINT UzytkownikPosilki_Uzytkownik_FK FOREIGN KEY 
    ( 
     ID_Uzytkownik1
    ) 
    REFERENCES Uzytkownik 
    ( 
     ID_Uzytkownik 
    ) 
    ON DELETE CASCADE 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
